//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaConsultaCEP.WSBuscaCEP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Endereco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string logradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                if ((object.ReferenceEquals(this.cepField, value) != true)) {
                    this.cepField = value;
                    this.RaisePropertyChanged("cep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.logradouroField, value) != true)) {
                    this.logradouroField = value;
                    this.RaisePropertyChanged("logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                if ((object.ReferenceEquals(this.bairroField, value) != true)) {
                    this.bairroField = value;
                    this.RaisePropertyChanged("bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.cidadeField, value) != true)) {
                    this.cidadeField = value;
                    this.RaisePropertyChanged("cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSBuscaCEP.WSBuscaCEPSoap")]
    public interface WSBuscaCEPSoap {
        
        // CODEGEN: Generating message contract since element name strCEP from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/endereco_por_CEP", ReplyAction="*")]
        PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponse endereco_por_CEP(PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/endereco_por_CEP", ReplyAction="*")]
        System.Threading.Tasks.Task<PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponse> endereco_por_CEPAsync(PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest request);
        
        // CODEGEN: Generating message contract since element name strUF from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEP_por_Endereco", ReplyAction="*")]
        PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponse CEP_por_Endereco(PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CEP_por_Endereco", ReplyAction="*")]
        System.Threading.Tasks.Task<PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponse> CEP_por_EnderecoAsync(PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endereco_por_CEPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="endereco_por_CEP", Namespace="http://tempuri.org/", Order=0)]
        public PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequestBody Body;
        
        public endereco_por_CEPRequest() {
        }
        
        public endereco_por_CEPRequest(PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class endereco_por_CEPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCEP;
        
        public endereco_por_CEPRequestBody() {
        }
        
        public endereco_por_CEPRequestBody(string strCEP) {
            this.strCEP = strCEP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class endereco_por_CEPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="endereco_por_CEPResponse", Namespace="http://tempuri.org/", Order=0)]
        public PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponseBody Body;
        
        public endereco_por_CEPResponse() {
        }
        
        public endereco_por_CEPResponse(PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class endereco_por_CEPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PaginaConsultaCEP.WSBuscaCEP.Endereco[] endereco_por_CEPResult;
        
        public endereco_por_CEPResponseBody() {
        }
        
        public endereco_por_CEPResponseBody(PaginaConsultaCEP.WSBuscaCEP.Endereco[] endereco_por_CEPResult) {
            this.endereco_por_CEPResult = endereco_por_CEPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CEP_por_EnderecoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CEP_por_Endereco", Namespace="http://tempuri.org/", Order=0)]
        public PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequestBody Body;
        
        public CEP_por_EnderecoRequest() {
        }
        
        public CEP_por_EnderecoRequest(PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CEP_por_EnderecoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUF;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strCidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strLogradouro;
        
        public CEP_por_EnderecoRequestBody() {
        }
        
        public CEP_por_EnderecoRequestBody(string strUF, string strCidade, string strLogradouro) {
            this.strUF = strUF;
            this.strCidade = strCidade;
            this.strLogradouro = strLogradouro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CEP_por_EnderecoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CEP_por_EnderecoResponse", Namespace="http://tempuri.org/", Order=0)]
        public PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponseBody Body;
        
        public CEP_por_EnderecoResponse() {
        }
        
        public CEP_por_EnderecoResponse(PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CEP_por_EnderecoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PaginaConsultaCEP.WSBuscaCEP.Endereco[] CEP_por_EnderecoResult;
        
        public CEP_por_EnderecoResponseBody() {
        }
        
        public CEP_por_EnderecoResponseBody(PaginaConsultaCEP.WSBuscaCEP.Endereco[] CEP_por_EnderecoResult) {
            this.CEP_por_EnderecoResult = CEP_por_EnderecoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBuscaCEPSoapChannel : PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBuscaCEPSoapClient : System.ServiceModel.ClientBase<PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap>, PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap {
        
        public WSBuscaCEPSoapClient() {
        }
        
        public WSBuscaCEPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBuscaCEPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBuscaCEPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBuscaCEPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponse PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap.endereco_por_CEP(PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest request) {
            return base.Channel.endereco_por_CEP(request);
        }
        
        public PaginaConsultaCEP.WSBuscaCEP.Endereco[] endereco_por_CEP(string strCEP) {
            PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest inValue = new PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest();
            inValue.Body = new PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequestBody();
            inValue.Body.strCEP = strCEP;
            PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponse retVal = ((PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap)(this)).endereco_por_CEP(inValue);
            return retVal.Body.endereco_por_CEPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponse> PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap.endereco_por_CEPAsync(PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest request) {
            return base.Channel.endereco_por_CEPAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPResponse> endereco_por_CEPAsync(string strCEP) {
            PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest inValue = new PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequest();
            inValue.Body = new PaginaConsultaCEP.WSBuscaCEP.endereco_por_CEPRequestBody();
            inValue.Body.strCEP = strCEP;
            return ((PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap)(this)).endereco_por_CEPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponse PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap.CEP_por_Endereco(PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest request) {
            return base.Channel.CEP_por_Endereco(request);
        }
        
        public PaginaConsultaCEP.WSBuscaCEP.Endereco[] CEP_por_Endereco(string strUF, string strCidade, string strLogradouro) {
            PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest inValue = new PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest();
            inValue.Body = new PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequestBody();
            inValue.Body.strUF = strUF;
            inValue.Body.strCidade = strCidade;
            inValue.Body.strLogradouro = strLogradouro;
            PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponse retVal = ((PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap)(this)).CEP_por_Endereco(inValue);
            return retVal.Body.CEP_por_EnderecoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponse> PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap.CEP_por_EnderecoAsync(PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest request) {
            return base.Channel.CEP_por_EnderecoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoResponse> CEP_por_EnderecoAsync(string strUF, string strCidade, string strLogradouro) {
            PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest inValue = new PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequest();
            inValue.Body = new PaginaConsultaCEP.WSBuscaCEP.CEP_por_EnderecoRequestBody();
            inValue.Body.strUF = strUF;
            inValue.Body.strCidade = strCidade;
            inValue.Body.strLogradouro = strLogradouro;
            return ((PaginaConsultaCEP.WSBuscaCEP.WSBuscaCEPSoap)(this)).CEP_por_EnderecoAsync(inValue);
        }
    }
}
